INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (101, N'General Male', 1000, N'Avaialbe')
INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (102, N'Private', 5000, N'Avaialbe')
INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (103, N'Private', 5000, N'Avaialbe')
INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (104, N'General Male', 3000, N'Avaialbe')
INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (105, N'Private', 5000, N'Not Avaialbe')
INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (201, N'General Female', 3000, N'Avaialbe')
INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (202, N'Private', 5000, N'Avaialbe')
INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (203, N'Semi Private', 3000, N'Not Avaialbe')
INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (204, N'Semi Private', 3000, N'Not Avaialbe')
INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (205, N'Semi Private', 3000, N'Not Avaialbe')
INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (301, N'General Female', 3000, N'Avaialbe')
INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (302, N'Semi Private', 3000, N'Avaialbe')
INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (303, N'Semi Private', 3000, N'Avaialbe')
INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (304, N'Private', 5000, N'Avaialbe')
INSERT INTO [dbo].[Rooms] ([Id], [type], [charges], [status]) VALUES (305, N'Private', 5000, N'Not Avaialbe')
