INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (111, N'Dr. Tatheer Fatima', N'Mon-Wed-Fri', N'6PM-9PM', 2200)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (112, N'Dr. Ahmed Hussain', N'Mon-Wed-Fri', N'9AM-11AM', NULL)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (113, N'Dr. Ahmer Abdullah', N'Mon-Tue-Fri', N'5PM-7PM', 2500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (114, N'Dr. Ibrahim Muhammad', N'Mon to Fri', N'2PM-3PM', 1500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (115, N'Dr. Ammar Iqbal', N'Mon-Wed-Fri', N'6PM-9PM', 1500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (116, N'Dr. Hassan Abdullah', N'Mon to Fri', N'2PM-3PM', 2500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (117, N'Dr. Kaneez Fatima', N'Mon-Wed-Fri', N'6PM-9PM', 1500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (118, N'Dr. Maheen Rahim', N'Mon-Wed-Fri', N'6PM-9PM', 2200)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (119, N'Dr. Zain Farzam', N'Mon-Tue-Fri', N'5PM-7PM', 1500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (120, N'Dr. Hamza Raza', N'Mon-Wed-Fri', N'6PM-9PM', 2500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (121, N'Dr. Shamama Hussain', N'Mon-Wed-Fri', N'6PM-9PM', 2200)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (122, N'Dr. Rubina Zahid', N'Mon-Tue-Fri', N'5PM-7PM', 2500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (123, N'Dr. Nauman Jahanzaib', N'Mon-Wed-Fri', N'6PM-9PM', 1500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (124, N'Dr. Namir Nishad', N'Mon-Wed-Fri', N'6PM-9PM', 2200)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (125, N'Dr. Masaad Hassam', N'Mon to Fri', N'2PM-3PM', 1500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (126, N'Dr. Hammad Kaashir', N'Mon-Wed-Fri', N'6PM-9PM', 2200)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (127, N'Dr. Ali Hussain', N'Mon-Wed-Fri', N'6PM-9PM', 2200)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (128, N'Dr. Bilal Hussain', N'Mon-Tue-Fri', N'5PM-7PM', 2500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (129, N'Dr. Umair Hussain', N'Mon-Wed-Fri', N'6PM-9PM', 1500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (130, N'Dr. Junaid Hussain', N'Mon to Fri', N'2PM-3PM', 2200)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (131, N'Dr. Saba Nauman', N'Mon-Tue-Fri', N'5PM-7PM', 2500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (132, N'Dr. Anum Bilal', N'Mon-Wed-Fri', N'6PM-9PM', 2500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (133, N'Dr. Asfad Jabbar', N'Mon to Fri', N'2PM-3PM', 2200)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (134, N'Dr. Zubair Shakoor', N'Mon-Tue-Fri', N'5PM-7PM', 1500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (135, N'Dr. Layma Fatima', N'Mon-Wed-Fri', N'6PM-9PM', 2500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (136, N'Dr. Kashif Tehzib', N'Mon-Wed-Fri', N'6PM-9PM', 2250)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (137, N'Dr. Saad Ahmed', N'Mon-Tue-Fri', N'5PM-7PM', 1500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (138, N'Dr. Muneer Omer', N'Mon-Wed-Fri', N'6PM-7PM', 2200)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (139, N'Dr. Jabeen Raza', N'Mon-Wed-Fri', N'6PM-7PM', 1500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (140, N'Dr. Tanzil Usmani', N'Mon-Wed-Fri', N'6PM-9PM', 2250)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (141, N'Dr. Ismail Saleem', N'Mon-Wed-Fri', N'6PM-9PM', 2200)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (142, N'Dr. Hanzala Khan', N'Mon-Tue-Fri', N'5PM-7PM', 1500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (143, N'Dr. Farham Fatima', N'Mon-Wed-Fri', N'6PM-9PM', 2200)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (144, N'Dr. Hammad Hanif', N'Mon-Wed-Fri', N'2500', 2500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (145, N'Dr. Mahnoor Usman', N'Mon-Tue-Fri', N'5PM-7PM', 1500)
INSERT INTO [dbo].[OPD1] ([Id], [Name], [Days], [Timings], [Fees]) VALUES (146, N'Dr. Zainab Ali', N'Mon to Fri', N'2PM To 3PM', 1200)
