INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1002, N'Dr. Ahmer', N'Abdullah', N'Male', N'N. Nazimabad', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1003, N'Dr. Ibrahim', N'Muhammad', N'Male', N'Bufferzone', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1004, N'Dr. Ammar', N'Iqbal', N'Male', N'N. Nazimabad', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1006, N'Dr. Maheen', N'Rahim', N'Female', N'Korangi', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1007, N'Dr. Zain', N'Farzam', N'Male', N'Landhi', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1008, N'Dr. Hamza', N'Raza', N'Male', N'DHA', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1009, N'Dr. Shamama', N'Hussain', N'Female', N'PECHS', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1010, N'Dr. Rubina', N'Zahid', N'Female', N'Gulshan', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1011, N'Dr. Nauman', N'Jahanzaib', N'Male', N'Jauhar', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1012, N'Dr. Namir', N'Nishad', N'Male', N'Surjani', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1013, N'Dr. Masaad', N'Hassam', N'Male', N'Nazimabad', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1014, N'Dr. Hammad', N'Kaashir', N'Male', N'Nazimabad', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1015, N'Dr. Ali', N'Hussain', N'Male', N'PECHS', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1016, N'Dr. Bilal', N'Hussain', N'Male', N'DHA', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1017, N'Dr. Umair', N'Hussain', N'Male', N'Gulshan', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1018, N'Dr. Junaid', N'Hussain', N'Male', N'Bufferzone', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1019, N'Dr. Saba', N'Nauman', N'Female', N'N. Nazimabad', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1020, N'Dr. Anum', N'Bilal', N'Female', N'North Karachi', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1021, N'Dr. Asfad', N'Jabbar', N'Male', N'North Karachi', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1022, N'Dr. Zubair', N'Shakoor', N'Male', N'N. Nazimabad', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1023, N'Dr. Layma', N'Ghafoor', N'Female', N'North Karachi', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1024, N'Dr. Kashif', N'Tehzib', N'Male', N'N. Nazimabad', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1025, N'Dr. Saad', N'Ahmed', N'Male', N'Bufferzone', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1026, N'Dr. Muneer', N'Omer', N'Male', N'North Karachi', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1027, N'Dr. Jabeen', N'Raza', N'Male', N'Bufferzone', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1028, N'Dr. Tanzil', N'Usmani', N'Male', N'North Karachi', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1029, N'Dr. Faris', N'Ali', N'Male', N'North Karachi', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (1030, N'Dr. Ismail', N'Saleem', N'Male', N'North Karachi', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (5642, N'Dr. Basmi', N'Azam', N'Male', N'Landhi', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (8892, N'Dr. Hanzala', N'Khanam', N'Male', N'Hyderi', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (8893, N'Dr. Farham', N'Fatima', N'Female', N'Shadman Town', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (8894, N'Dr. Hammad', N'Kashif', N'Male', N'Jamshed Town', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (8895, N'Dr Mahnoor', N'Usman', N'Female', N'North Krachi', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (8901, N'Dr. Abdur', N'Rehman', N'Male', N'North Karachi', 1000)
INSERT INTO [dbo].[Doc_Data1] ([DocID], [FirstName], [SecondName], [Gender], [DocAddress], [Fee]) VALUES (8902, N'Dr. Zainab', N'Ali', N'Female', N'Jauhar', 1000)
